# First, create a ConfigMap whose contents are used
# as the nginx.conf file in the web server.
# This server uses /var/www/html as its
# root document directory. When the server gets a
# request for *.php, it will forward that request
# to our PHP-FPM container.


# CAUTION: All changes here might have to be reflected in /.docker/nginx/conf.d/default.conf !!!
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: my-awesome-project-ns
data:
  default.conf: |
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
    
      index index.php index.html;
      server_name localhost;
      access_log /dev/stdout;
      error_log /dev/stderr;
    
      # Set nginx to serve files from the shared volume!
      root /code;
      server_name _;
    
      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param REQUEST_METHOD $request_method;
      }
    }
